apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: linkus-front-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1beta2
        kind: Deployment
        name: linkus-front
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
