apiVersion: v1
kind: Service
metadata:
    name: linkus-back-lb
spec:
    type: LoadBalancer
    ports:
        - port: 80
          protocol: TCP
          targetPort: 8088
    selector:
        app: linkus-back
