apiVersion: v1
kind: Service
metadata:
    name: todolist-middle-redis-lb
spec:
    type: LoadBalancer
    ports:
        - port: 80
          protocol: TCP
          targetPort: 6379
    selector:
        app: todolist-middle-redis
